version: '3.8'

# networks:
#   corp:
#     driver: bridge

services:
  backend:
    container_name: odin
    build:
      context: ./
      cache_from:
        - my-base-image:nx-base
      dockerfile: ./apps/odin/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: odin:nx-dev
    ports:
      - 3333:3333
    # environment:
    #   NODE_ENV: 'development'
    #   PORT: 4939
    # networks:
    #   - corp
    restart: on-failure
  frontend:
    container_name: luzon
    build:
      context: ./
      dockerfile: ./apps/luzon/Dockerfile
      # cache_from:
      #   - nginx:1.19.2
      # args:
      #   NODE_ENV: 'development'
      #   BUILD_FLAG: ''
    volumes:
      - frontend_build:/app/builder/dist/apps/luzon
    image: luzon:nx-dev
    # ports:
    #   - 4200:8080
    # environment:
    #   NODE_ENV: 'development'
    #   PORT: 4200
    # networks:
    #   - corp
    restart: on-failure
  webserver:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/var/www/luzon
    depends_on:
      - frontend
volumes:
  frontend_build:
